// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/OrgVariantLanes.tsx": () => import("../components/mockups/OrgVariantLanes.tsx"),
  "./components/mockups/OrgVariantPipeline.tsx": () => import("../components/mockups/OrgVariantPipeline.tsx"),
  "./components/mockups/OrgVariantRadial.tsx": () => import("../components/mockups/OrgVariantRadial.tsx"),
  "./components/mockups/OrgVariantRoster.tsx": () => import("../components/mockups/OrgVariantRoster.tsx"),
  "./components/mockups/OrganigramaClientum.tsx": () => import("../components/mockups/OrganigramaClientum.tsx"),
  "./components/mockups/clientum-landing/Current.tsx": () => import("../components/mockups/clientum-landing/Current.tsx"),
  "./components/mockups/clientum-landing/RefinedA.tsx": () => import("../components/mockups/clientum-landing/RefinedA.tsx"),
  "./components/mockups/clientum-landing/RefinedB.tsx": () => import("../components/mockups/clientum-landing/RefinedB.tsx"),
  "./components/mockups/crm-pipeline/AccessibleReadable.tsx": () => import("../components/mockups/crm-pipeline/AccessibleReadable.tsx"),
  "./components/mockups/crm-pipeline/ClearHierarchy.tsx": () => import("../components/mockups/crm-pipeline/ClearHierarchy.tsx"),
  "./components/mockups/crm-pipeline/ConfidentDepth.tsx": () => import("../components/mockups/crm-pipeline/ConfidentDepth.tsx"),
  "./components/mockups/crm-pipeline/Current.tsx": () => import("../components/mockups/crm-pipeline/Current.tsx"),
  "./components/mockups/crm-pipeline/ExplicitAffordances.tsx": () => import("../components/mockups/crm-pipeline/ExplicitAffordances.tsx"),
  "./components/mockups/crm-pipeline/TightenedHierarchy.tsx": () => import("../components/mockups/crm-pipeline/TightenedHierarchy.tsx")
};
